Tracker:AddLocations("locations/A Sinister Turn (Protoss).json")
Tracker:AddLocations("locations/A Sinister Turn (Terran).json")
Tracker:AddLocations("locations/A Sinister Turn (Zerg).json")
Tracker:AddLocations("locations/All-In (Protoss).json")
Tracker:AddLocations("locations/All-In (Terran).json")
Tracker:AddLocations("locations/All-In (Zerg).json")
Tracker:AddLocations("locations/Amons Fall.json")
Tracker:AddLocations("locations/Amons Reach (Protoss).json")
Tracker:AddLocations("locations/Amons Reach (Terran).json")
Tracker:AddLocations("locations/Amons Reach (Zerg).json")
Tracker:AddLocations("locations/Back in the Saddle.json")
Tracker:AddLocations("locations/Belly of the Beast.json")
Tracker:AddLocations("locations/Breakout.json")
Tracker:AddLocations("locations/Brothers in Arms (Protoss).json")
Tracker:AddLocations("locations/Brothers in Arms (Terran).json")
Tracker:AddLocations("locations/Brothers in Arms (Zerg).json")
Tracker:AddLocations("locations/Conviction.json")
Tracker:AddLocations("locations/Cutthroat (Protoss).json")
Tracker:AddLocations("locations/Cutthroat (Terran).json")
Tracker:AddLocations("locations/Cutthroat (Zerg).json")
Tracker:AddLocations("locations/Dark Skies.json")
Tracker:AddLocations("locations/Dark Whispers (Protoss).json")
Tracker:AddLocations("locations/Dark Whispers (Terran).json")
Tracker:AddLocations("locations/Dark Whispers (Zerg).json")
Tracker:AddLocations("locations/Death From Above (Protoss).json")
Tracker:AddLocations("locations/Death From Above (Terran).json")
Tracker:AddLocations("locations/Death From Above (Zerg).json")
Tracker:AddLocations("locations/Devils Playground (Protoss).json")
Tracker:AddLocations("locations/Devils Playground (Terran).json")
Tracker:AddLocations("locations/Devils Playground (Zerg).json")
Tracker:AddLocations("locations/Domination (Protoss).json")
Tracker:AddLocations("locations/Domination (Terran).json")
Tracker:AddLocations("locations/Domination (Zerg).json")
Tracker:AddLocations("locations/Echoes of the Future (Protoss).json")
Tracker:AddLocations("locations/Echoes of the Future (Terran).json")
Tracker:AddLocations("locations/Echoes of the Future (Zerg).json")
Tracker:AddLocations("locations/End Game.json")
Tracker:AddLocations("locations/Enemy Intelligence.json")
Tracker:AddLocations("locations/Enemy Within.json")
Tracker:AddLocations("locations/Engine of Destruction (Protoss).json")
Tracker:AddLocations("locations/Engine of Destruction (Terran).json")
Tracker:AddLocations("locations/Engine of Destruction (Zerg).json")
Tracker:AddLocations("locations/Evacuation (Protoss).json")
Tracker:AddLocations("locations/Evacuation (Terran).json")
Tracker:AddLocations("locations/Evacuation (Zerg).json")
Tracker:AddLocations("locations/Evil Awoken.json")
Tracker:AddLocations("locations/Fire in the Sky (Protoss).json")
Tracker:AddLocations("locations/Fire in the Sky (Terran).json")
Tracker:AddLocations("locations/Fire in the Sky (Zerg).json")
Tracker:AddLocations("locations/Flashpoint.json")
Tracker:AddLocations("locations/For Aiur!.json")
Tracker:AddLocations("locations/Forbidden Weapon (Protoss).json")
Tracker:AddLocations("locations/Forbidden Weapon (Terran).json")
Tracker:AddLocations("locations/Forbidden Weapon (Zerg).json")
Tracker:AddLocations("locations/Gates of Hell (Protoss).json")
Tracker:AddLocations("locations/Gates of Hell (Terran).json")
Tracker:AddLocations("locations/Gates of Hell (Zerg).json")
Tracker:AddLocations("locations/Ghost of a Chance.json")
Tracker:AddLocations("locations/Ghosts in the Fog (Protoss).json")
Tracker:AddLocations("locations/Ghosts in the Fog (Terran).json")
Tracker:AddLocations("locations/Ghosts in the Fog (Zerg).json")
Tracker:AddLocations("locations/Hand of Darkness (Protoss).json")
Tracker:AddLocations("locations/Hand of Darkness (Terran).json")
Tracker:AddLocations("locations/Hand of Darkness (Zerg).json")
Tracker:AddLocations("locations/Harbinger of Oblivion (Protoss).json")
Tracker:AddLocations("locations/Harbinger of Oblivion (Terran).json")
Tracker:AddLocations("locations/Harbinger of Oblivion (Zerg).json")
Tracker:AddLocations("locations/Harvest of Screams (Protoss).json")
Tracker:AddLocations("locations/Harvest of Screams (Terran).json")
Tracker:AddLocations("locations/Harvest of Screams (Zerg).json")
Tracker:AddLocations("locations/Havens Fall (Protoss).json")
Tracker:AddLocations("locations/Havens Fall (Terran).json")
Tracker:AddLocations("locations/Havens Fall (Zerg).json")
Tracker:AddLocations("locations/In Utter Darkness (Protoss).json")
Tracker:AddLocations("locations/In Utter Darkness (Terran).json")
Tracker:AddLocations("locations/In Utter Darkness (Zerg).json")
Tracker:AddLocations("locations/In the Enemys Shadow.json")
Tracker:AddLocations("locations/Infested (Protoss).json")
Tracker:AddLocations("locations/Infested (Terran).json")
Tracker:AddLocations("locations/Infested (Zerg).json")
Tracker:AddLocations("locations/Into the Void.json")
Tracker:AddLocations("locations/Lab Rat (Protoss).json")
Tracker:AddLocations("locations/Lab Rat (Terran).json")
Tracker:AddLocations("locations/Lab Rat (Zerg).json")
Tracker:AddLocations("locations/Last Stand (Protoss).json")
Tracker:AddLocations("locations/Last Stand (Terran).json")
Tracker:AddLocations("locations/Last Stand (Zerg).json")
Tracker:AddLocations("locations/Liberation Day.json")
Tracker:AddLocations("locations/Maw of the Void (Protoss).json")
Tracker:AddLocations("locations/Maw of the Void (Terran).json")
Tracker:AddLocations("locations/Maw of the Void (Zerg).json")
Tracker:AddLocations("locations/Media Blitz (Protoss).json")
Tracker:AddLocations("locations/Media Blitz (Terran).json")
Tracker:AddLocations("locations/Media Blitz (Zerg).json")
Tracker:AddLocations("locations/Night Terrors.json")
Tracker:AddLocations("locations/Old Soldiers (Protoss).json")
Tracker:AddLocations("locations/Old Soldiers (Terran).json")
Tracker:AddLocations("locations/Old Soldiers (Zerg).json")
Tracker:AddLocations("locations/Outbreak (Protoss).json")
Tracker:AddLocations("locations/Outbreak (Terran).json")
Tracker:AddLocations("locations/Outbreak (Zerg).json")
Tracker:AddLocations("locations/Phantoms of the Void (Protoss).json")
Tracker:AddLocations("locations/Phantoms of the Void (Terran).json")
Tracker:AddLocations("locations/Phantoms of the Void (Zerg).json")
Tracker:AddLocations("locations/Piercing the Shroud.json")
Tracker:AddLocations("locations/Planetfall (Protoss).json")
Tracker:AddLocations("locations/Planetfall (Terran).json")
Tracker:AddLocations("locations/Planetfall (Zerg).json")
Tracker:AddLocations("locations/Purification (Protoss).json")
Tracker:AddLocations("locations/Purification (Terran).json")
Tracker:AddLocations("locations/Purification (Zerg).json")
Tracker:AddLocations("locations/RakShir (Protoss).json")
Tracker:AddLocations("locations/RakShir (Terran).json")
Tracker:AddLocations("locations/RakShir (Zerg).json")
Tracker:AddLocations("locations/Rendezvous (Protoss).json")
Tracker:AddLocations("locations/Rendezvous (Terran).json")
Tracker:AddLocations("locations/Rendezvous (Zerg).json")
Tracker:AddLocations("locations/Safe Haven (Protoss).json")
Tracker:AddLocations("locations/Safe Haven (Terran).json")
Tracker:AddLocations("locations/Safe Haven (Zerg).json")
Tracker:AddLocations("locations/Salvation (Protoss).json")
Tracker:AddLocations("locations/Salvation (Terran).json")
Tracker:AddLocations("locations/Salvation (Zerg).json")
Tracker:AddLocations("locations/Shatter the Sky (Protoss).json")
Tracker:AddLocations("locations/Shatter the Sky (Terran).json")
Tracker:AddLocations("locations/Shatter the Sky (Zerg).json")
Tracker:AddLocations("locations/Shoot the Messenger (Protoss).json")
Tracker:AddLocations("locations/Shoot the Messenger (Terran).json")
Tracker:AddLocations("locations/Shoot the Messenger (Zerg).json")
Tracker:AddLocations("locations/Sky Shield (Protoss).json")
Tracker:AddLocations("locations/Sky Shield (Terran).json")
Tracker:AddLocations("locations/Sky Shield (Zerg).json")
Tracker:AddLocations("locations/Smash and Grab (Protoss).json")
Tracker:AddLocations("locations/Smash and Grab (Terran).json")
Tracker:AddLocations("locations/Smash and Grab (Zerg).json")
Tracker:AddLocations("locations/Steps of the Rite (Protoss).json")
Tracker:AddLocations("locations/Steps of the Rite (Terran).json")
Tracker:AddLocations("locations/Steps of the Rite (Zerg).json")
Tracker:AddLocations("locations/Sudden Strike.json")
Tracker:AddLocations("locations/Supernova (Protoss).json")
Tracker:AddLocations("locations/Supernova (Terran).json")
Tracker:AddLocations("locations/Supernova (Zerg).json")
Tracker:AddLocations("locations/Supreme.json")
Tracker:AddLocations("locations/Templars Charge (Protoss).json")
Tracker:AddLocations("locations/Templars Charge (Terran).json")
Tracker:AddLocations("locations/Templars Charge (Zerg).json")
Tracker:AddLocations("locations/Templars Return.json")
Tracker:AddLocations("locations/Temple of Unification (Protoss).json")
Tracker:AddLocations("locations/Temple of Unification (Terran).json")
Tracker:AddLocations("locations/Temple of Unification (Zerg).json")
Tracker:AddLocations("locations/The Crucible (Protoss).json")
Tracker:AddLocations("locations/The Crucible (Terran).json")
Tracker:AddLocations("locations/The Crucible (Zerg).json")
Tracker:AddLocations("locations/The Dig (Protoss).json")
Tracker:AddLocations("locations/The Dig (Terran).json")
Tracker:AddLocations("locations/The Dig (Zerg).json")
Tracker:AddLocations("locations/The Escape.json")
Tracker:AddLocations("locations/The Essence of Eternity.json")
Tracker:AddLocations("locations/The Great Train Robbery (Protoss).json")
Tracker:AddLocations("locations/The Great Train Robbery (Terran).json")
Tracker:AddLocations("locations/The Great Train Robbery (Zerg).json")
Tracker:AddLocations("locations/The Growing Shadow (Protoss).json")
Tracker:AddLocations("locations/The Growing Shadow (Terran).json")
Tracker:AddLocations("locations/The Growing Shadow (Zerg).json")
Tracker:AddLocations("locations/The Host (Protoss).json")
Tracker:AddLocations("locations/The Host (Terran).json")
Tracker:AddLocations("locations/The Host (Zerg).json")
Tracker:AddLocations("locations/The Infinite Cycle.json")
Tracker:AddLocations("locations/The Moebius Factor (Protoss).json")
Tracker:AddLocations("locations/The Moebius Factor (Terran).json")
Tracker:AddLocations("locations/The Moebius Factor (Zerg).json")
Tracker:AddLocations("locations/The Outlaws (Protoss).json")
Tracker:AddLocations("locations/The Outlaws (Terran).json")
Tracker:AddLocations("locations/The Outlaws (Zerg).json")
Tracker:AddLocations("locations/The Reckoning (Protoss).json")
Tracker:AddLocations("locations/The Reckoning (Terran).json")
Tracker:AddLocations("locations/The Reckoning (Zerg).json")
Tracker:AddLocations("locations/The Spear of Adun (Protoss).json")
Tracker:AddLocations("locations/The Spear of Adun (Terran).json")
Tracker:AddLocations("locations/The Spear of Adun (Zerg).json")
Tracker:AddLocations("locations/Trouble In Paradise.json")
Tracker:AddLocations("locations/Unsealing the Past (Protoss).json")
Tracker:AddLocations("locations/Unsealing the Past (Terran).json")
Tracker:AddLocations("locations/Unsealing the Past (Zerg).json")
Tracker:AddLocations("locations/Waking the Ancient (Protoss).json")
Tracker:AddLocations("locations/Waking the Ancient (Terran).json")
Tracker:AddLocations("locations/Waking the Ancient (Zerg).json")
Tracker:AddLocations("locations/Welcome to the Jungle (Protoss).json")
Tracker:AddLocations("locations/Welcome to the Jungle (Terran).json")
Tracker:AddLocations("locations/Welcome to the Jungle (Zerg).json")
Tracker:AddLocations("locations/Whispers of Doom.json")
Tracker:AddLocations("locations/With Friends Like These.json")
Tracker:AddLocations("locations/Zero Hour (Protoss).json")
Tracker:AddLocations("locations/Zero Hour (Terran).json")
Tracker:AddLocations("locations/Zero Hour (Zerg).json")
Tracker:AddLocations("locations/Overworld.json")
